#!/bin/bash

FILE="core-image-khepri-orange-pi-3lts.rootfs-2026"


echo "rm"
rm ${FILE}*.wic*

echo "cp"
cp ../build-orangepi3/tmp/deploy/images/orange-pi-3lts/${FILE}*.wic.gz .

echo "gunzip"
gunzip ${FILE}*.wic.gz

echo "dd"
sudo dd if=$(ls ${FILE}*.wic) of=/dev/sda bs=4M status=progress

echo "sync"
sync

echo "rm"
rm ${FILE}*.wic*

echo "done"
