# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

LAYER_BASE := "${TOPDIR}/.."

BBLAYERS ?= " \
  ${LAYER_BASE}/poky/meta \
  ${LAYER_BASE}/poky/meta-poky \
  ${LAYER_BASE}/poky/meta-yocto-bsp \
  ${LAYER_BASE}/meta-openembedded/meta-oe \
  ${LAYER_BASE}/meta-openembedded/meta-networking \
  ${LAYER_BASE}/meta-openembedded/meta-python \
  ${LAYER_BASE}/meta-openembedded/meta-filesystems \
  ${LAYER_BASE}/meta-arm/meta-arm \
  ${LAYER_BASE}/meta-arm/meta-arm-toolchain \
  ${LAYER_BASE}/meta-sunxi \
  ${LAYER_BASE}/meta-local \
  "
