# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""


BBLAYERS ?= " \
  /home/max/projects/orangepi3-sdr/poky/meta \
  /home/max/projects/orangepi3-sdr/poky/meta-poky \
  /home/max/projects/orangepi3-sdr/poky/meta-yocto-bsp \
  /home/max/projects/orangepi3-sdr/meta-openembedded/meta-oe \
  /home/max/projects/orangepi3-sdr/meta-openembedded/meta-networking \
  /home/max/projects/orangepi3-sdr/meta-openembedded/meta-python \
  /home/max/projects/orangepi3-sdr/meta-openembedded/meta-filesystems \
  /home/max/projects/orangepi3-sdr/meta-arm/meta-arm \
  /home/max/projects/orangepi3-sdr/meta-arm/meta-arm-toolchain \
  /home/max/projects/orangepi3-sdr/meta-sunxi \
  /home/max/projects/orangepi3-sdr/meta-local \
  "
