server.document-root = "/usr/share/wifi-setup/www"
server.port = 80
server.bind = "0.0.0.0"
server.modules = ( "mod_cgi" )
server.pid-file = "/run/lighttpd-wifi-setup.pid"
server.errorlog = "/tmp/lighttpd-wifi-setup.error.log"
server.breakagelog = "/tmp/lighttpd-wifi-setup.breakage.log"

index-file.names = ( "index.html" )

$HTTP["url"] =~ "^/cgi-bin/" {
  cgi.assign = ( "" => "" )
}
